/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.epam.shamuradova.gradle.task1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        StringUtils classUnderTest = new StringUtils();
        assertFalse(classUnderTest.isPositiveNumber("-5"));
        
    }
}
